/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        cream: {
          50: '#FDFCF8',
          100: '#F8F7F3',
          200: '#F0EDE4',
          300: '#E3DECC',
          400: '#D4CBAD',
          500: '#C5B98E',
          600: '#B89567',
          700: '#9A7B55',
          800: '#7D6245',
          900: '#5C4A34',
        },
        sage: {
          50: '#F4F7F3',
          100: '#E2EBDF',
          200: '#C5D6BF',
          300: '#A3BC9A',
          400: '#7FA178',
          500: '#5C7A5D',
          600: '#4A624B',
          700: '#3A4E3C',
          800: '#2C3B2E',
          900: '#1D271E',
        },
        gold: {
          50: '#FDF9F2',
          100: '#F9EFDA',
          200: '#F2DEB3',
          300: '#E8C788',
          400: '#DDB05C',
          500: '#B89567',
          600: '#9A7B55',
          700: '#7D6245',
          800: '#604A36',
          900: '#423228',
        },
        text: {
          primary: '#232323',
          secondary: '#4A4A4A',
          muted: '#757575',
          inverse: '#FFFFFF',
        },
        surface: {
          cream: '#F8F7F3',
          white: '#FFFFFF',
          sage: '#5C7A5D',
          dark: '#232323',
        },
        border: {
          light: '#E8E6E1',
          medium: '#D4D0C8',
          accent: '#5C7A5D',
        },
        success: '#22C55E',
        warning: '#F59E0B',
        error: '#EF4444',
      },
      fontFamily: {
        serif: ['var(--font-serif)', 'Playfair Display', 'Cormorant Garamond', 'Georgia', 'serif'],
        sans: ['var(--font-sans)', 'Inter', 'system-ui', 'sans-serif'],
      },
      spacing: {
        section: '6rem',
        'section-lg': '10rem',
        'page-top': '8rem',
      },
      fontSize: {
        'display-xl': ['clamp(3.5rem, 8vw, 5.625rem)', { lineHeight: '1', letterSpacing: '-0.03em' }],
        'display-lg': ['clamp(3rem, 7vw, 4.5rem)', { lineHeight: '1.05', letterSpacing: '-0.03em' }],
        'display': ['clamp(2.5rem, 5vw, 3.5rem)', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-sm': ['clamp(2rem, 3.5vw, 2.5rem)', { lineHeight: '1.15', letterSpacing: '-0.02em' }],
        'heading-1': ['clamp(2.5rem, 5vw, 3.5rem)', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'heading-2': ['clamp(2rem, 3.5vw, 3rem)', { lineHeight: '1.15', letterSpacing: '-0.02em' }],
        'heading-3': ['clamp(1.5rem, 2.5vw, 2rem)', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'heading-4': ['clamp(1.125rem, 1.5vw, 1.5rem)', { lineHeight: '1.3', letterSpacing: '0' }],
        'body-lg': ['clamp(1.125rem, 1.25vw, 1.5rem)', { lineHeight: '1.6' }],
        'body': ['clamp(0.9375rem, 1vw, 1.125rem)', { lineHeight: '1.6' }],
        'body-sm': ['0.9375rem', { lineHeight: '1.5' }],
        'small': ['0.8125rem', { lineHeight: '1.4' }],
        'micro': ['0.75rem', { lineHeight: '1.3' }],
        'number-massive': ['clamp(4rem, 12vw, 8rem)', { lineHeight: '0.85', letterSpacing: '-0.03em' }],
        'number-lg': ['clamp(3rem, 6vw, 5rem)', { lineHeight: '0.9', letterSpacing: '-0.03em' }],
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.25rem',
        '4xl': '1.5rem',
        '5xl': '2rem',
      },
      animation: {
        'fade-up': 'fadeUp 0.6s ease-out forwards',
        'fade-left': 'fadeLeft 0.6s ease-out forwards',
        'fade-right': 'fadeRight 0.6s ease-out forwards',
        'scale-in': 'scaleIn 0.6s ease-out forwards',
        'blur-reveal': 'blurReveal 0.8s ease-out forwards',
        'float': 'float 6s ease-in-out infinite',
        'float-delayed': 'float 6s ease-in-out 2s infinite',
        'pulse-slow': 'pulseSlow 4s ease-in-out infinite',
        'drift-slow': 'driftSlow 15s ease-in-out infinite',
        'scroll-indicator': 'scrollBounce 2s ease-in-out infinite',
        'counter': 'counter 2s ease-out forwards',
        'accordion-down': 'accordionDown 0.3s ease-out',
        'accordion-up': 'accordionUp 0.3s ease-out',
        'ripple': 'ripple 0.6s ease-out',
      },
      keyframes: {
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(30px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeLeft: {
          from: { opacity: '0', transform: 'translateX(-30px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        fadeRight: {
          from: { opacity: '0', transform: 'translateX(30px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        blurReveal: {
          from: { opacity: '0', filter: 'blur(10px)', transform: 'translateY(20px)' },
          to: { opacity: '1', filter: 'blur(0)', transform: 'translateY(0)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        pulseSlow: {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '0.8' },
        },
        driftSlow: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '33%': { transform: 'translate(20px, -20px)' },
          '66%': { transform: 'translate(-15px, 15px)' },
        },
        scrollBounce: {
          '0%, 100%': { transform: 'translateY(0)', opacity: '0.4' },
          '50%': { transform: 'translateY(8px)', opacity: '1' },
        },
        accordionDown: {
          from: { height: '0', opacity: '0' },
          to: { height: 'var(--accordion-height)', opacity: '1' },
        },
        accordionUp: {
          from: { height: 'var(--accordion-height)', opacity: '1' },
          to: { height: '0', opacity: '0' },
        },
        ripple: {
          from: { transform: 'scale(0)', opacity: '0.5' },
          to: { transform: 'scale(4)', opacity: '0' },
        },
      },
    },
  },
  plugins: [],
}
